# 1. Datos de tu base de datos (sacados de tu captura de Workbench)
spring.datasource.url=jdbc:mysql://100.55.238.48:3306/uniraite_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=diego
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración para que Java hable con MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Puerto del servidor
server.port=8080